[[constraint]]
  name = "github.com/Comcast/codex"
  version= "0.1.5"

[[constraint]]
  branch = "master"
  name = "github.com/Comcast/webpa-common"

[[override]]
  name = "github.com/prometheus/client_golang"
  version = "v0.9.2"

[[override]]
  name = "github.com/ugorji/go"
  revision = "v1.1.1"

[prune]
  go-tests = true
  unused-packages = true
